name: Pull & Sync
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  pull:
    name: Pull & Sync
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull the latest articles
        run: python mcContents.py pull

      - name: Sync with the MCBBS collection
        run: node sync

      - name: Commit the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "SPGlove"
          git add .
          git diff-index --quiet HEAD || git commit -m ":arrows_counterclockwise: pull and sync"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
